== QTM 385

'''''

=== Homework 1

Student: 2297846

'''''

== FAQ

[arabic]
. What are the criteria for full marks?

____
Two. Half of your grade is based on coding, and the other half is based
on getting the results right.
____

[arabic, start=2]
. How to write a clean code?

____
Check out the PEP 8 Manual
https://www.python.org/dev/peps/pep-0008/[here]. But in a nutshell:
___

___
* Indents should be four spaces (not tab)
* Limit all lines to a maximum of 79 characters (long blocks of text is
limited to 72 characters)
* Use a space after a comma
* Use a space before and after arithmetic operators
____

[arabic, start=3]
. How to get the question right?

____
Answer to what has been asked. Not more, not less. Check twice that you
did right and answered all the parts of the question. Like a good
carpenter, measure twice, but cut only once: check your answers before
submitting them.
____

[arabic, start=4]
. How do I submit my homework?

____
Two methods:
___

___
* Upload your Jupyter Notebook to your Github page. Put the Github link
on Canvas, and I’ll check (recommended).
___

___
* Upload your Jupyter Notebook on Canvas (not recommended).
____

[arabic, start=5]
. What to do if I have other questions?

____
Sign up for office hours using
https://calendly.com/umberto-mignozzetti/office-hours[this link.]
____

*Good luck!*

'''''

== Question 1

Run the following code:

....
0.1 + 0.1 + 0.1
....

Is it equal to `0.3`? If not, why?


+*In[1]:*+
[source, ipython3]
----
# No because the stored values are the nearest binary fraction, not the actual number since they are floats. Therefore, the code would equal approximately .3 when values are added together.
----

'''''

== Question 2

How many digits has latexmath:[$3^{1,000,000}$]? (Hint: the function
`str` transforms a number into a string.)


+*In[2]:*+
[source, ipython3]
----
# 477122
----

'''''

== Question 3

Create a tuple with three foods that you love to eat. Save it in a
variable called `preferred_food`.


+*In[7]:*+
[source, ipython3]
----
preferred_food=("coconut","blueberries","plantain")
print(preferred_food)
----


+*Out[7]:*+
----
('coconut', 'blueberries', 'plantain')
----

'''''

== Question 4

The module random has a handy function for selecting elements in a
tuple: `choice`. Import the module `random`, and name it `rd`.


+*In[8]:*+
[source, ipython3]
----
import random as rd
----

'''''

== Question 5

Using the function choice, select a food to eat today. (Hint: when we
used `numpy`, I named it `np`. When I needed a function in it, I did
`np.function_I_needed`…)


+*In[10]:*+
[source, ipython3]
----
print(rd.choice(preferred_food)) 
----


+*Out[10]:*+
----
coconut
----

*That’s all, folks!*


+*In[ ]:*+
[source, ipython3]
----

----


+*In[ ]:*+
[source, ipython3]
----

----
